### ISSUE TITLE
Firefox gradient issue

### ISSUE THREAD

**Issue by pavodev** [adrianhajdin/project_hoobank#2]
Hi, great video!
I'm not sure if I'm missing something out but gradients in the hero section are much stronger in Firefox. 

- **Chrome:**
<img width="1157" alt="Screenshot 2022-08-18 at 22 27 30" src="https://user-images.githubusercontent.com/47891529/185488899-7c21a911-b27d-4501-add7-54e98b3d38d7.png">
- **Firefox:**
<img width="1209" alt="Screenshot 2022-08-18 at 22 27 17" src="https://user-images.githubusercontent.com/47891529/185488936-71fe117f-0a01-4e0b-b12f-b916db5bdada.png">

**Comment by hardiktheprogrammer** [comment]
yes , is also not support on firefox 
 
* {
  scroll-behaviour: smooth;

}

**Comment by 1sma31L** [comment]
till now no clear solution for this issue as firefox can't allow more than 100px filter blur i did this to make it match the design a little bit for firefox
```css
.pink__gradient {
	background: linear-gradient(90deg, #f4c4f3 0%, #fc67fa 100%);
	filter: blur(100px); //max value in firefox is 100px
	opacity: 0.2;
}
```
